[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "backend"
source = "backend"

[[services]]
name = "frontend"
source = "frontend"

[services.backend]
build.command = "npm run railway:build"
start.command = "npm run railway:start"

[services.frontend]
build.command = "npm run railway:build"
start.command = "npm run railway:start"